version: "3"

services:

  db: 
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"

  load:
    build:
      context: .
    environment:
      - DB_HOSTNAME=db
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE
      - CONSUMER_KEY
      - CONSUMER_SECRET
      - ACCESS_TOKEN
      - ACCESS_TOKEN_SECRET
      - TRACK
    links:
      - db
    depends_on:
      - db
    entrypoint: "wait-for-it db:5432 -- npm run migrate-and-start"
